INSERT INTO `picture`
(`id`, `flat_id`, `src`                                                  ) VALUES
( 1,   1,         '/assets/img/content/01-dwarf-house.png'               ),
( 2,   1,         '/assets/img/content/02-green-block.png'               ),
( 3,   1,         '/assets/img/content/03-edges.png'                     ),
( 4,   1,         '/assets/img/content/04-three-houses.png'              ),
( 5,   1,         '/assets/img/content/05-rainbow-cake.png'              ),
( 6,   1,         '/assets/img/content/06-three-blocks.png'              ),
( 7,   1,         '/assets/img/content/07-block-and-tent.png'            ),
( 8,   1,         '/assets/img/content/08-hourglass-house.png'           ),
( 9,   1,         '/assets/img/content/09-black-and-white-house.png'     ),
(10,   1,         '/assets/img/content/10-modern-lomonosov.png'          ),
(11,   1,         '/assets/img/content/11-wigwam.png'                    ),
(12,   1,         '/assets/img/content/12-earth-hut.png'                 ),
(13,   1,         '/assets/img/content/13-unordered-reversed-rainbow.png'),
(14,   1,         '/assets/img/content/14-igloos-from-above.png'         ),
(15,   1,         '/assets/img/content/15-three-mushroom-houses.png'     ),
(16,   2,         '/assets/img/content/16-squares-random.png'            ),
(17,   2,         '/assets/img/content/17-block-with-two-circles.png'    ),
(18,   3,         '/assets/img/content/18-house-with-tree.png'           );
