INSERT INTO `picture`
(`id`, `department_id`, `src`                                             ) VALUES
( 1,   1,         '/assets/img/content/01-apple.png'                      ),
( 2,   1,         '/assets/img/content/02-sunflower.png'                  ),
( 3,   1,         '/assets/img/content/03-cubic-trees.png'                ),
( 4,   1,         '/assets/img/content/04-ladder.png'                     ),
( 5,   1,         '/assets/img/content/05-stars.png'                      ),
( 6,   1,         '/assets/img/content/06-ship.png'                       ),
( 7,   1,         '/assets/img/content/07-meadow-and-fish.png'            ),
( 8,   1,         '/assets/img/content/08-moon-and-stars.png'             ),
( 9,   1,         '/assets/img/content/09-dotted-ball.png'                ),
(10,   1,         '/assets/img/content/10-pumpkin.png'                    ),
(11,   1,         '/assets/img/content/11-t-shirt.png'                    ),
(12,   1,         '/assets/img/content/12-jug.png'                        ),
(13,   1,         '/assets/img/content/13-dotted-napkin.png'              ),
(14,   1,         '/assets/img/content/14-eggs-in-a-basket-with-water.png'),
(15,   1,         '/assets/img/content/15-car.png'                        ),
(16,   2,         '/assets/img/content/16-tv-set.png'                     ),
(17,   2,         '/assets/img/content/17-mushroom.png'                   ),
(18,   3,         '/assets/img/content/18-bug.png'                        );
